# Generated by Django 4.0.5 on 2022-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_sheet', models.IntegerField(unique=True, verbose_name='Порядок заказа в листе')),
                ('order_numer', models.BigIntegerField(verbose_name='Номер заказа')),
                ('price_usd', models.FloatField(verbose_name='Стоимость в долларах')),
                ('price_rub', models.FloatField(verbose_name='Стоимость в рублях')),
                ('delivery_date', models.DateField(verbose_name='Срок поставки ')),
            ],
            options={
                'verbose_name': 'Подробности заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
    ]
