# Generated by Django 4.0.5 on 2022-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price_rub',
            field=models.IntegerField(verbose_name='Стоимость в рублях'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price_usd',
            field=models.IntegerField(verbose_name='Стоимость в долларах'),
        ),
    ]
