# Generated by Django 4.0.5 on 2022-06-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_order_numer_orderdetail_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='delivery_date',
            field=models.DateField(verbose_name='Срок поставки'),
        ),
    ]
